// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mlagents/envs/communicator_objects/unity_output.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct UnityOutput {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var rlOutput: UnityRLOutput {
    get {return _storage._rlOutput ?? UnityRLOutput()}
    set {_uniqueStorage()._rlOutput = newValue}
  }
  /// Returns true if `rlOutput` has been explicitly set.
  var hasRlOutput: Bool {return _storage._rlOutput != nil}
  /// Clears the value of `rlOutput`. Subsequent reads from it will return its default value.
  mutating func clearRlOutput() {_uniqueStorage()._rlOutput = nil}

  var rlInitializationOutput: UnityRLInitializationOutput {
    get {return _storage._rlInitializationOutput ?? UnityRLInitializationOutput()}
    set {_uniqueStorage()._rlInitializationOutput = newValue}
  }
  /// Returns true if `rlInitializationOutput` has been explicitly set.
  var hasRlInitializationOutput: Bool {return _storage._rlInitializationOutput != nil}
  /// Clears the value of `rlInitializationOutput`. Subsequent reads from it will return its default value.
  mutating func clearRlInitializationOutput() {_uniqueStorage()._rlInitializationOutput = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "communicator_objects"

extension UnityOutput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnityOutput"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "rl_output"),
    2: .standard(proto: "rl_initialization_output"),
  ]

  fileprivate class _StorageClass {
    var _rlOutput: UnityRLOutput? = nil
    var _rlInitializationOutput: UnityRLInitializationOutput? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _rlOutput = source._rlOutput
      _rlInitializationOutput = source._rlInitializationOutput
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._rlOutput)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._rlInitializationOutput)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._rlOutput {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if let v = _storage._rlInitializationOutput {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: UnityOutput, rhs: UnityOutput) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._rlOutput != rhs_storage._rlOutput {return false}
        if _storage._rlInitializationOutput != rhs_storage._rlInitializationOutput {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
