// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mlagents/envs/communicator_objects/unity_input.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct UnityInput {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var rlInput: UnityRLInput {
    get {return _storage._rlInput ?? UnityRLInput()}
    set {_uniqueStorage()._rlInput = newValue}
  }
  /// Returns true if `rlInput` has been explicitly set.
  var hasRlInput: Bool {return _storage._rlInput != nil}
  /// Clears the value of `rlInput`. Subsequent reads from it will return its default value.
  mutating func clearRlInput() {_uniqueStorage()._rlInput = nil}

  var rlInitializationInput: UnityRLInitializationInput {
    get {return _storage._rlInitializationInput ?? UnityRLInitializationInput()}
    set {_uniqueStorage()._rlInitializationInput = newValue}
  }
  /// Returns true if `rlInitializationInput` has been explicitly set.
  var hasRlInitializationInput: Bool {return _storage._rlInitializationInput != nil}
  /// Clears the value of `rlInitializationInput`. Subsequent reads from it will return its default value.
  mutating func clearRlInitializationInput() {_uniqueStorage()._rlInitializationInput = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "communicator_objects"

extension UnityInput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnityInput"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "rl_input"),
    2: .standard(proto: "rl_initialization_input"),
  ]

  fileprivate class _StorageClass {
    var _rlInput: UnityRLInput? = nil
    var _rlInitializationInput: UnityRLInitializationInput? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _rlInput = source._rlInput
      _rlInitializationInput = source._rlInitializationInput
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._rlInput)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._rlInitializationInput)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._rlInput {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if let v = _storage._rlInitializationInput {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: UnityInput, rhs: UnityInput) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._rlInput != rhs_storage._rlInput {return false}
        if _storage._rlInitializationInput != rhs_storage._rlInitializationInput {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
