// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mlagents/envs/communicator_objects/unity_rl_initialization_output.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The request message containing the academy's parameters.
struct UnityRLInitializationOutput {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var version: String {
    get {return _storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  var logPath: String {
    get {return _storage._logPath}
    set {_uniqueStorage()._logPath = newValue}
  }

  var brainParameters: [BrainParametersProto] {
    get {return _storage._brainParameters}
    set {_uniqueStorage()._brainParameters = newValue}
  }

  var environmentParameters: EnvironmentParametersProto {
    get {return _storage._environmentParameters ?? EnvironmentParametersProto()}
    set {_uniqueStorage()._environmentParameters = newValue}
  }
  /// Returns true if `environmentParameters` has been explicitly set.
  var hasEnvironmentParameters: Bool {return _storage._environmentParameters != nil}
  /// Clears the value of `environmentParameters`. Subsequent reads from it will return its default value.
  mutating func clearEnvironmentParameters() {_uniqueStorage()._environmentParameters = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "communicator_objects"

extension UnityRLInitializationOutput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnityRLInitializationOutput"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "version"),
    3: .standard(proto: "log_path"),
    5: .standard(proto: "brain_parameters"),
    6: .standard(proto: "environment_parameters"),
  ]

  fileprivate class _StorageClass {
    var _name: String = String()
    var _version: String = String()
    var _logPath: String = String()
    var _brainParameters: [BrainParametersProto] = []
    var _environmentParameters: EnvironmentParametersProto? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _version = source._version
      _logPath = source._logPath
      _brainParameters = source._brainParameters
      _environmentParameters = source._environmentParameters
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._name)
        case 2: try decoder.decodeSingularStringField(value: &_storage._version)
        case 3: try decoder.decodeSingularStringField(value: &_storage._logPath)
        case 5: try decoder.decodeRepeatedMessageField(value: &_storage._brainParameters)
        case 6: try decoder.decodeSingularMessageField(value: &_storage._environmentParameters)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 1)
      }
      if !_storage._version.isEmpty {
        try visitor.visitSingularStringField(value: _storage._version, fieldNumber: 2)
      }
      if !_storage._logPath.isEmpty {
        try visitor.visitSingularStringField(value: _storage._logPath, fieldNumber: 3)
      }
      if !_storage._brainParameters.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._brainParameters, fieldNumber: 5)
      }
      if let v = _storage._environmentParameters {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: UnityRLInitializationOutput, rhs: UnityRLInitializationOutput) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._version != rhs_storage._version {return false}
        if _storage._logPath != rhs_storage._logPath {return false}
        if _storage._brainParameters != rhs_storage._brainParameters {return false}
        if _storage._environmentParameters != rhs_storage._environmentParameters {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
